import "./world-cell-theater.css";
import * as THREE from "three";
import { sha256 } from "@noble/hashes/sha2.js";

const q=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const video=q<HTMLVideoElement>("camera"), canvas=q<HTMLCanvasElement>("stage");
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:"high-performance"});
const scene=new THREE.Scene(), camera3=new THREE.PerspectiveCamera(52,1,.01,100);
camera3.position.set(0,0,2.4); scene.add(new THREE.AmbientLight(0xffffff,1));
const geometry=new THREE.BufferGeometry();
const material=new THREE.PointsMaterial({size:.018,vertexColors:true,sizeAttenuation:true,transparent:true,opacity:.96});
const cloud=new THREE.Points(geometry,material); scene.add(cloud);
const grid=new THREE.GridHelper(4,32,0x1c5770,0x102433); grid.rotation.x=Math.PI/2; grid.position.z=-1.6; scene.add(grid);

interface Point{x:number;y:number;z:number;r:number;g:number;b:number;c:number;t:number}
interface Moment{id:string;created:number;points:Point[];pose:number[];sensor:string;backend:string;inputHash:string;outputHash:string;receipt:string}
interface WorldCell{version:21;id:string;branch:string;created:number;moments:Moment[];pha:string;memoryCapsule:string;rootprint:string;evidence:Evidence[]}
interface Evidence{time:number;kind:string;device:string;transport:string;input:string;output:string;receipt:string;hardware:boolean;details:Record<string,unknown>}
let stream:MediaStream|null=null, running=false, frameNo=0, points:Point[]=[], moments:Moment[]=[], currentMoment=0, playTimer=0;
let gpuDevice:GPUDevice|null=null, gpuAdapterName="CPU REFERENCE", backend="CPU REFERENCE";
let pc:RTCPeerConnection|null=null, channel:RTCDataChannel|null=null, pendingChunks:Uint8Array[]=[], expectedDigest="", expectedBytes=0;
const evidence:Evidence[]=[];
const encoder=new TextEncoder();
const hex=(b:Uint8Array)=>Array.from(b,x=>x.toString(16).padStart(2,"0")).join("");
const digest=(v:unknown)=>hex(sha256(encoder.encode(typeof v==="string"?v:JSON.stringify(v))));
const setText=(id:string,v:string)=>q(id).textContent=v;

function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera3.aspect=r.width/r.height;camera3.updateProjectionMatrix()}
new ResizeObserver(resize).observe(canvas);
function render(){cloud.rotation.y+=running?.0015:.00035;renderer.render(scene,camera3);requestAnimationFrame(render)}render();

function updateCloud(p:Point[]){const pos=new Float32Array(p.length*3), col=new Float32Array(p.length*3);for(let i=0;i<p.length;i++){const v=p[i]!;pos.set([v.x,v.y,v.z],i*3);col.set([v.r,v.g,v.b],i*3)}geometry.setAttribute("position",new THREE.BufferAttribute(pos,3));geometry.setAttribute("color",new THREE.BufferAttribute(col,3));geometry.computeBoundingSphere();setText("surfel-count",String(p.length))}
function updateTimeline(){const el=q("timeline");el.innerHTML="";if(!moments.length){el.innerHTML='<span class="empty">No Moments committed.</span>';return}moments.forEach((m,i)=>{const b=document.createElement("button");b.className=i===currentMoment?"active":"";b.innerHTML=`<small>MOMENT ${String(i).padStart(2,"0")}</small><b>${m.points.length} SURFELS</b>`;b.onclick=()=>showMoment(i);el.appendChild(b)});const slider=q<HTMLInputElement>("replay-slider");slider.max=String(moments.length-1);slider.value=String(currentMoment);q<HTMLButtonElement>("prev-button").disabled=false;q<HTMLButtonElement>("next-button").disabled=false;q<HTMLButtonElement>("play-button").disabled=false;q<HTMLButtonElement>("seal-button").disabled=false}
function showMoment(i:number){if(!moments.length)return;currentMoment=Math.max(0,Math.min(i,moments.length-1));updateCloud(moments[currentMoment]!.points);updateTimeline();setText("cell-state",`WORLD CELL / MOMENT ${currentMoment}`)}

async function probeGpu(){try{const nav=navigator as Navigator&{gpu?:GPU};if(!nav.gpu)throw new Error("WebGPU unavailable");const adapter=await nav.gpu.requestAdapter({powerPreference:"high-performance"});if(!adapter)throw new Error("No adapter");gpuDevice=await adapter.requestDevice();gpuAdapterName=(adapter.info?.description||adapter.info?.device||"WEBGPU ADAPTER").toUpperCase();backend="WEBGPU COMPUTE";setText("gpu-badge","ACTIVE");setText("compute-state","WEBGPU");setText("backend-name",backend);setText("adapter-name",gpuAdapterName)}catch{setText("gpu-badge","CPU FALLBACK");setText("backend-name",backend);setText("adapter-name","PORTABLE")}}
probeGpu();

async function gpuTransform(samples:Float32Array){if(!gpuDevice)return samples;const shader=gpuDevice.createShaderModule({code:`@group(0) @binding(0) var<storage,read> src:array<f32>;@group(0) @binding(1) var<storage,read_write> dst:array<f32>;@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id:vec3<u32>){let i=id.x;if(i<arrayLength(&src)){dst[i]=src[i];}}`});const src=gpuDevice.createBuffer({size:samples.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});const dst=gpuDevice.createBuffer({size:samples.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});const read=gpuDevice.createBuffer({size:samples.byteLength,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});gpuDevice.queue.writeBuffer(src,0,samples);const pipeline=gpuDevice.createComputePipeline({layout:"auto",compute:{module:shader,entryPoint:"main"}});const bind=gpuDevice.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:src}},{binding:1,resource:{buffer:dst}}]});const cmd=gpuDevice.createCommandEncoder();const pass=cmd.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil(samples.length/64));pass.end();cmd.copyBufferToBuffer(dst,0,read,0,samples.byteLength);gpuDevice.queue.submit([cmd.finish()]);await read.mapAsync(GPUMapMode.READ);const out=new Float32Array(read.getMappedRange().slice(0));read.unmap();src.destroy();dst.destroy();read.destroy();return out}

function orientationPose(){const o=screen.orientation?.angle||0;return [1,0,0,0,1,0,0,0,1,Math.sin(o*Math.PI/180)*.03,0,0]}
async function captureFrame(){if(!running||video.readyState<2)return;const w=160,h=Math.max(90,Math.round(160*video.videoHeight/video.videoWidth));const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{willReadFrequently:true})!;ctx.drawImage(video,0,0,w,h);const img=ctx.getImageData(0,0,w,h);const stride=3, fresh:Point[]=[];const packed:number[]=[];for(let y=0;y<h;y+=stride){for(let x=0;x<w;x+=stride){const i=(y*w+x)*4,r=img.data[i]!/255,g=img.data[i+1]!/255,b=img.data[i+2]!/255;const lum=.2126*r+.7152*g+.0722*b;const depth=.75+(1-lum)*.95;const nx=(x/w-.5)*depth*1.45,ny=-(y/h-.5)*depth*(h/w)*1.45,nz=-depth;packed.push(nx,ny,nz,r,g,b);fresh.push({x:nx,y:ny,z:nz,r,g,b,c:.5+lum*.5,t:performance.now()})}}
const start=performance.now();const transformed=await gpuTransform(new Float32Array(packed));for(let i=0,j=0;i<fresh.length;i++,j+=6){fresh[i]!.x=transformed[j]!;fresh[i]!.y=transformed[j+1]!;fresh[i]!.z=transformed[j+2]!}points=mergePoints(points,fresh,48000);updateCloud(points);frameNo++;setText("frame-count",String(frameNo));setText("dispatch-time",`${(performance.now()-start).toFixed(1)} ms`);q("compute-meter").style.width=`${Math.min(100,20+points.length/480)}%`;setText("pose-state",`TRACK ${frameNo}`);if(frameNo%12===0)recordEvidence("reconstruction",fresh)}
function mergePoints(a:Point[],b:Point[],max:number){const map=new Map<string,Point>();for(const p of [...a,...b]){const k=`${Math.round(p.x*45)}:${Math.round(p.y*45)}:${Math.round(p.z*45)}`;const old=map.get(k);map.set(k,old?{x:(old.x+p.x)/2,y:(old.y+p.y)/2,z:(old.z+p.z)/2,r:(old.r+p.r)/2,g:(old.g+p.g)/2,b:(old.b+p.b)/2,c:Math.min(1,(old.c+p.c)/2+.03),t:p.t}:p);if(map.size>=max)break}return [...map.values()]}
function recordEvidence(kind:string,output:unknown,device=navigator.userAgent,transport="browser",hardware=!!gpuDevice,details:Record<string,unknown>={}){const input=digest(`${kind}:${frameNo}:${performance.now()}`),out=digest(output);const e={time:Date.now(),kind,device,transport,input,output:out,receipt:digest({kind,input,out,device,transport}),hardware,details};evidence.push(e);q("evidence-log").textContent=JSON.stringify(evidence,null,2)}

async function startCamera(){stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();running=true;frameNo=0;q<HTMLButtonElement>("start-button").disabled=true;q<HTMLButtonElement>("capture-button").disabled=false;q<HTMLButtonElement>("stop-button").disabled=false;setText("capture-state","CAPTURING");q("stage-message").style.display="none";const loop=async()=>{if(!running)return;await captureFrame();setTimeout(loop,gpuDevice?110:190)};loop();recordEvidence("camera-open",{tracks:stream.getVideoTracks().map(t=>t.getSettings())})}
function stopCamera(){running=false;stream?.getTracks().forEach(t=>t.stop());stream=null;q<HTMLButtonElement>("start-button").disabled=false;q<HTMLButtonElement>("capture-button").disabled=true;q<HTMLButtonElement>("stop-button").disabled=true;setText("capture-state","READY")}
function commitMoment(){if(!points.length)return;const p=points.map(x=>({...x})),inputHash=digest({frameNo,p:orientationPose()}),outputHash=digest(p);const m:Moment={id:`moment-${moments.length}`,created:Date.now(),points:p,pose:orientationPose(),sensor:setTextValue("sensor-badge"),backend,inputHash,outputHash,receipt:digest({inputHash,outputHash,parent:moments.at(-1)?.receipt||"0"})};moments.push(m);currentMoment=moments.length-1;updateTimeline();recordEvidence("moment",m);setText("cell-state",`WORLD CELL / ${moments.length} MOMENTS`)}
const setTextValue=(id:string)=>q(id).textContent||"";
function buildCell():WorldCell{const base={version:21 as const,id:"",branch:"main",created:Date.now(),moments,pha:digest("tessaryn/pha/v21"),memoryCapsule:digest({moments:moments.map(m=>m.receipt)}),rootprint:"",evidence};const rootprint=digest({...base,rootprint:undefined,id:undefined});return {...base,id:rootprint,rootprint}}
function seal(){const cell=buildCell();setText("rootprint",cell.rootprint.slice(0,16).toUpperCase());setText("cell-state",`WORLD CELL / SEALED / ${moments.length} MOMENTS`);recordEvidence("seal",cell,"browser-crypto","SHA-256",false,{rootprint:cell.rootprint});q<HTMLButtonElement>("send-button").disabled=!channel||channel.readyState!=="open"}

function setupPeer(){pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.onconnectionstatechange=()=>setText("peer-state",pc?.connectionState.toUpperCase()||"CLOSED");pc.ondatachannel=e=>attachChannel(e.channel);return pc}
function attachChannel(ch:RTCDataChannel){channel=ch;channel.binaryType="arraybuffer";channel.onopen=()=>{setText("channel-state","OPEN");q<HTMLButtonElement>("send-button").disabled=!moments.length};channel.onclose=()=>setText("channel-state","CLOSED");channel.onmessage=onPeerMessage}
const waitIce=(p:RTCPeerConnection)=>new Promise<void>(resolve=>{if(p.iceGatheringState==="complete")return resolve();p.onicegatheringstatechange=()=>p.iceGatheringState==="complete"&&resolve()});
async function createOffer(){const p=setupPeer();attachChannel(p.createDataChannel("tessaryn-world-cell",{ordered:true}));await p.setLocalDescription(await p.createOffer());await waitIce(p);q<HTMLTextAreaElement>("pairing-text").value=JSON.stringify(p.localDescription);setText("transfer-state","Offer created. Copy it to the joining device.")}
async function joinOffer(){const raw=q<HTMLTextAreaElement>("pairing-text").value.trim();if(!raw)return;const p=setupPeer();await p.setRemoteDescription(JSON.parse(raw));await p.setLocalDescription(await p.createAnswer());await waitIce(p);q<HTMLTextAreaElement>("pairing-text").value=JSON.stringify(p.localDescription);setText("transfer-state","Answer created. Copy it back to the offering device.")}
async function applyAnswer(){if(!pc)throw new Error("Create an offer first");await pc.setRemoteDescription(JSON.parse(q<HTMLTextAreaElement>("pairing-text").value));setText("transfer-state","Answer applied. Waiting for the encrypted data channel.")}
async function sendCell(){if(!channel||channel.readyState!=="open")return;const bytes=encoder.encode(JSON.stringify(buildCell())),full=hex(sha256(bytes)),chunk=32*1024,total=Math.ceil(bytes.length/chunk);channel.send(JSON.stringify({type:"manifest",digest:full,bytes:bytes.length,chunks:total}));for(let i=0;i<total;i++){const part=bytes.slice(i*chunk,(i+1)*chunk);channel.send(part);q("transfer-meter").style.width=`${Math.round((i+1)/total*100)}%`;await new Promise(r=>setTimeout(r,8))}channel.send(JSON.stringify({type:"complete"}));setText("transfer-state",`Sent ${bytes.length.toLocaleString()} verified bytes.`);recordEvidence("webrtc-send",{bytes:bytes.length,digest:full},"peer","WebRTC DataChannel",true)}
function onPeerMessage(e:MessageEvent){if(typeof e.data==="string"){const msg=JSON.parse(e.data);if(msg.type==="manifest"){pendingChunks=[];expectedDigest=msg.digest;expectedBytes=msg.bytes;setText("transfer-state",`Receiving ${msg.bytes.toLocaleString()} bytes…`)}else if(msg.type==="complete")void finalizeReceive();return}pendingChunks.push(new Uint8Array(e.data));const got=pendingChunks.reduce((n,c)=>n+c.length,0);q("transfer-meter").style.width=`${Math.min(100,Math.round(got/expectedBytes*100))}%`}
async function finalizeReceive(){const bytes=new Uint8Array(expectedBytes);let off=0;for(const c of pendingChunks){bytes.set(c,off);off+=c.length}const actual=hex(sha256(bytes));if(actual!==expectedDigest){setText("transfer-state","REJECTED / canonical digest mismatch");return}const cell=JSON.parse(new TextDecoder().decode(bytes)) as WorldCell;const calculated=digest({...cell,rootprint:undefined,id:undefined});if(calculated!==cell.rootprint){setText("transfer-state","REJECTED / World Cell Rootprint mismatch");return}moments=cell.moments;evidence.splice(0,evidence.length,...cell.evidence);currentMoment=Math.max(0,moments.length-1);updateTimeline();showMoment(currentMoment);setText("rootprint",cell.rootprint.slice(0,16).toUpperCase());setText("transfer-state",`VERIFIED / World Cell reconstructed from ${bytes.length.toLocaleString()} bytes.`);recordEvidence("webrtc-receive",{bytes:bytes.length,digest:actual},"peer","WebRTC DataChannel",true)}

async function connectSerial(){const n=navigator as Navigator&{serial?:{requestPort():Promise<any>}};if(!n.serial)throw new Error("WebSerial unavailable");const port=await n.serial.requestPort();await port.open({baudRate:3000000});setText("sensor-badge","EVENT CAMERA");setText("sensor-detail","External event-camera stream connected through WebSerial.");q("sensor-log").textContent="WebSerial event camera connected. Expecting newline-delimited JSON packets with x, y, polarity, timestamp_ns, confidence.";recordEvidence("sensor-connect",{port:"serial"},"external-event-camera","WebSerial",true);const reader=port.readable.getReader();let buffer="";for(;;){const {value,done}=await reader.read();if(done)break;buffer+=new TextDecoder().decode(value);let nl;while((nl=buffer.indexOf("\n"))>=0){const line=buffer.slice(0,nl);buffer=buffer.slice(nl+1);try{const ev=JSON.parse(line);const p:Point={x:(ev.x/640-.5)*1.3,y:-(ev.y/480-.5),z:-1+(ev.polarity?.02:-.02),r:ev.polarity?1:.1,g:.6,b:ev.polarity?.2:1,c:ev.confidence??1,t:ev.timestamp_ns??performance.now()};points=mergePoints(points,[p],48000);updateCloud(points)}catch{}}}}
async function connectUsb(){const n=navigator as Navigator&{usb?:{requestDevice(o:{filters:any[]}):Promise<any>}};if(!n.usb)throw new Error("WebUSB unavailable");const device=await n.usb.requestDevice({filters:[]});await device.open();setText("sensor-badge","USB SENSOR");q("sensor-log").textContent=`Connected ${device.productName||"USB spatial sensor"}. Vendor ${device.vendorId}, product ${device.productId}.`;recordEvidence("sensor-connect",{vendorId:device.vendorId,productId:device.productId},device.productName||"USB sensor","WebUSB",true)}
async function probeXr(){const xr=(navigator as Navigator&{xr?:XRSystem}).xr;if(!xr||!await xr.isSessionSupported("immersive-ar")){q("sensor-log").textContent="WebXR immersive AR/depth is not exposed by this browser.";return}q("sensor-log").textContent="WebXR immersive AR is available. Depth sensing will be requested by a native/installed AR host session.";setText("sensor-badge","WEBXR READY");recordEvidence("sensor-probe",{immersiveAR:true},"phone-depth","WebXR",true)}

q("start-button").onclick=()=>void startCamera().catch(e=>setText("stage-message",String(e)));
q("stop-button").onclick=stopCamera;q("capture-button").onclick=commitMoment;q("seal-button").onclick=seal;
q<HTMLInputElement>("replay-slider").oninput=e=>showMoment(Number((e.target as HTMLInputElement).value));q("prev-button").onclick=()=>showMoment(currentMoment-1);q("next-button").onclick=()=>showMoment(currentMoment+1);q("play-button").onclick=()=>{if(playTimer){clearInterval(playTimer);playTimer=0;setText("play-button","PLAY");return}setText("play-button","STOP");playTimer=window.setInterval(()=>showMoment((currentMoment+1)%moments.length),900)};
q("host-button").onclick=()=>void createOffer();q("join-button").onclick=()=>void joinOffer();q("answer-button").onclick=()=>void applyAnswer();q("send-button").onclick=()=>void sendCell();
q("sensor-button").onclick=()=>q<HTMLDialogElement>("sensor-dialog").showModal();q("evidence-button").onclick=()=>q<HTMLDialogElement>("evidence-dialog").showModal();document.querySelectorAll<HTMLElement>("[data-close]").forEach(b=>b.onclick=()=>q<HTMLDialogElement>(b.dataset.close!).close());q("serial-button").onclick=()=>void connectSerial().catch(e=>q("sensor-log").textContent=String(e));q("usb-button").onclick=()=>void connectUsb().catch(e=>q("sensor-log").textContent=String(e));q("xr-button").onclick=()=>void probeXr();q("reset-button").onclick=()=>{stopCamera();points=[];moments=[];evidence.length=0;updateCloud([]);updateTimeline();setText("rootprint","UNSEALED");setText("cell-state","WORLD CELL / EMPTY")};
window.addEventListener("beforeunload",stopCamera);navigator.serviceWorker?.register("./sw.js").catch(()=>{});updateTimeline();