#include "keyxym/v20.hpp"
#include "keyxym/sha256.hpp"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>
#include <limits>
#include <stdexcept>

namespace keyxym { namespace {
void u32(std::vector<Byte>&o,std::uint32_t v){for(int i=3;i>=0;--i)o.push_back(Byte(v>>(i*8)));}
void u64(std::vector<Byte>&o,std::uint64_t v){for(int i=7;i>=0;--i)o.push_back(Byte(v>>(i*8)));}
void f32(std::vector<Byte>&o,float v){std::uint32_t b{};std::memcpy(&b,&v,4);u32(o,b);}
void str(std::vector<Byte>&o,const std::string&s){u64(o,s.size());o.insert(o.end(),s.begin(),s.end());}
void hash(std::vector<Byte>&o,const Hash256&h){o.insert(o.end(),h.begin(),h.end());}
void domain(std::vector<Byte>&o,const char*d){str(o,d);}
std::uint64_t ns(Timestamp t){return static_cast<std::uint64_t>(t.time_since_epoch().count());}
Timestamp from_ns(std::uint64_t v){return Timestamp(std::chrono::nanoseconds(v));}
void surfel(std::vector<Byte>&o,const Surfel&s){f32(o,s.x);f32(o,s.y);f32(o,s.z);f32(o,s.nx);f32(o,s.ny);f32(o,s.nz);f32(o,s.r);f32(o,s.g);f32(o,s.b);f32(o,s.confidence);u64(o,s.timestamp_offset);}
Hash256 surfels_root(const std::vector<Surfel>&v){std::vector<Byte>o;domain(o,"keyxym/formal/surfels/v20");u64(o,v.size());for(const auto&s:v)surfel(o,s);return sha256(o);}
Hash256 tagged(const char*d,const Hash256&h){std::vector<Byte>o;domain(o,d);hash(o,h);return sha256(o);}
bool finite(const Surfel&s){const float v[]={s.x,s.y,s.z,s.nx,s.ny,s.nz,s.r,s.g,s.b,s.confidence};return std::all_of(std::begin(v),std::end(v),[](float x){return std::isfinite(x);});}
class Reader{const std::vector<Byte>&b;std::size_t p{};void need(std::size_t n)const{if(n>b.size()-p)throw std::runtime_error("truncated formal World Cell");}public:explicit Reader(const std::vector<Byte>&x):b(x){}Byte B(){need(1);return b[p++];}std::uint32_t U32(){need(4);std::uint32_t v{};for(int i=0;i<4;++i)v=(v<<8)|b[p++];return v;}std::uint64_t U64(){need(8);std::uint64_t v{};for(int i=0;i<8;++i)v=(v<<8)|b[p++];return v;}float F32(){auto x=U32();float v{};std::memcpy(&v,&x,4);return v;}std::string S(std::uint64_t m){auto n=U64();if(n>m)throw std::runtime_error("string exceeds limit");need(std::size_t(n));std::string s(reinterpret_cast<const char*>(b.data()+p),std::size_t(n));p+=std::size_t(n);return s;}Hash256 H(){need(32);Hash256 h{};for(auto&x:h)x=b[p++];return h;}bool done()const{return p==b.size();}};
Surfel read_surfel(Reader&r){Surfel s;s.x=r.F32();s.y=r.F32();s.z=r.F32();s.nx=r.F32();s.ny=r.F32();s.nz=r.F32();s.r=r.F32();s.g=r.F32();s.b=r.F32();s.confidence=r.F32();s.timestamp_offset=r.U64();return s;}
}

Hash256 compute_formal_moment_rootprint(const FormalMoment&m){std::vector<Byte>o;domain(o,"keyxym/formal/moment/v20");str(o,m.id);u64(o,ns(m.start_time));u64(o,ns(m.end_time));hash(o,surfels_root(m.surfels));hash(o,m.parent_moment);hash(o,m.evidence);return sha256(o);}
FormalValidation validate_formal_world_cell(const FormalWorldCell&c,const FormalLimits&l){if(c.id.size()>l.max_identifier_bytes)return{false,"identifier exceeds limit"};if(c.branch.empty()||c.branch.size()>l.max_branch_bytes)return{false,"invalid branch"};if(c.base_geometry.size()>l.max_surfels)return{false,"base geometry exceeds limit"};if(c.moments.size()>l.max_moments)return{false,"moment count exceeds limit"};auto ok=[](const Surfel&s){return finite(s)&&s.confidence>=0&&s.confidence<=1;};for(const auto&s:c.base_geometry)if(!ok(s))return{false,"invalid base surfel"};std::uint64_t total=c.base_geometry.size();Hash256 parent{};for(const auto&m:c.moments){if(m.id.empty()||m.id.size()>l.max_identifier_bytes)return{false,"invalid moment id"};if(m.end_time<m.start_time)return{false,"reversed moment interval"};if(m.surfels.size()>l.max_surfels-total)return{false,"total surfels exceed limit"};total+=m.surfels.size();for(const auto&s:m.surfels)if(!ok(s))return{false,"invalid moment surfel"};if(m.parent_moment!=parent)return{false,"non-canonical moment lineage"};auto root=compute_formal_moment_rootprint(m);if(m.rootprint!=Hash256{}&&m.rootprint!=root)return{false,"moment rootprint mismatch"};parent=root;}return{true,{}};}
Hash256 FormalWorldCell::compute_rootprint()const{auto v=validate_formal_world_cell(*this);if(!v.valid)throw std::invalid_argument(v.error);std::vector<Hash256>leaves;leaves.push_back(tagged("keyxym/formal/geometry/v20",surfels_root(base_geometry)));Hash256 parent{};for(const auto&m:moments){auto copy=m;copy.parent_moment=parent;auto root=compute_formal_moment_rootprint(copy);leaves.push_back(tagged("keyxym/formal/moment-leaf/v20",root));parent=root;}leaves.push_back(tagged("keyxym/formal/pha/v20",pha));leaves.push_back(tagged("keyxym/formal/memory/v20",memory_capsule));leaves.push_back(tagged("keyxym/formal/parent-cell/v20",parent_rootprint));std::vector<Byte>b;domain(b,"keyxym/formal/world-cell/v20");str(b,branch);for(const auto&h:leaves)hash(b,h);return sha256(b);}
void FormalWorldCell::seal(const SignatureProvider&p,const std::vector<Byte>&k){provenance.content_hash=surfels_root(base_geometry);provenance.rootprint=compute_rootprint();provenance.creation_time=std::chrono::system_clock::now();provenance.version=formal_world_cell_version;provenance.creator_signature=p.sign(provenance.rootprint,k);id=hex(provenance.rootprint);}
bool FormalWorldCell::verify(const SignatureProvider&p,const std::vector<Byte>&k)const{try{return provenance.version==formal_world_cell_version&&provenance.rootprint==compute_rootprint()&&id==hex(provenance.rootprint)&&p.verify(provenance.rootprint,provenance.creator_signature,k);}catch(...){return false;}}
std::vector<Byte> serialize_formal_world_cell(const FormalWorldCell&c,const FormalLimits&l){auto v=validate_formal_world_cell(c,l);if(!v.valid)throw std::invalid_argument(v.error);std::vector<Byte>o;domain(o,"keyxym/formal/world-cell/canonical/v20");u32(o,formal_world_cell_version);str(o,c.id);str(o,c.branch);u64(o,c.base_geometry.size());for(const auto&s:c.base_geometry)surfel(o,s);u64(o,c.moments.size());for(const auto&m:c.moments){str(o,m.id);u64(o,ns(m.start_time));u64(o,ns(m.end_time));u64(o,m.surfels.size());for(const auto&s:m.surfels)surfel(o,s);hash(o,m.parent_moment);hash(o,m.evidence);hash(o,m.rootprint);}hash(o,c.provenance.content_hash);hash(o,c.provenance.manifest_hash);hash(o,c.provenance.rootprint);o.insert(o.end(),c.provenance.creator_signature.begin(),c.provenance.creator_signature.end());u64(o,ns(c.provenance.creation_time));u64(o,c.provenance.version);hash(o,c.pha);hash(o,c.memory_capsule);hash(o,c.parent_rootprint);return o;}
FormalWorldCell deserialize_formal_world_cell(const std::vector<Byte>&b,const FormalLimits&l){Reader r(b);if(r.S(128)!="keyxym/formal/world-cell/canonical/v20"||r.U32()!=formal_world_cell_version)throw std::runtime_error("unsupported formal format");FormalWorldCell c;c.id=r.S(l.max_identifier_bytes);c.branch=r.S(l.max_branch_bytes);auto n=r.U64();if(n>l.max_surfels)throw std::runtime_error("base geometry exceeds limit");for(std::uint64_t i=0;i<n;++i)c.base_geometry.push_back(read_surfel(r));auto mn=r.U64();if(mn>l.max_moments)throw std::runtime_error("moment count exceeds limit");std::uint64_t total=n;for(std::uint64_t i=0;i<mn;++i){FormalMoment m;m.id=r.S(l.max_identifier_bytes);m.start_time=from_ns(r.U64());m.end_time=from_ns(r.U64());auto sn=r.U64();if(sn>l.max_surfels-total)throw std::runtime_error("total surfels exceed limit");total+=sn;for(std::uint64_t j=0;j<sn;++j)m.surfels.push_back(read_surfel(r));m.parent_moment=r.H();m.evidence=r.H();m.rootprint=r.H();c.moments.push_back(std::move(m));}c.provenance.content_hash=r.H();c.provenance.manifest_hash=r.H();c.provenance.rootprint=r.H();for(auto&x:c.provenance.creator_signature)x=r.B();c.provenance.creation_time=from_ns(r.U64());c.provenance.version=r.U64();c.pha=r.H();c.memory_capsule=r.H();c.parent_rootprint=r.H();if(!r.done())throw std::runtime_error("trailing formal bytes");auto v=validate_formal_world_cell(c,l);if(!v.valid)throw std::runtime_error(v.error);return c;}
FormalWorldCell migrate_world_cell_v2(const WorldCell&x,std::string branch){FormalWorldCell c;c.id=x.id;c.branch=std::move(branch);c.base_geometry=x.base_geometry;c.provenance=x.provenance;c.pha=x.pha;c.memory_capsule=x.memory_capsule;c.parent_rootprint=x.parent_rootprint;Hash256 parent{};for(std::size_t i=0;i<x.temporal_moments.size();++i){FormalMoment m;m.id="moment-"+std::to_string(i);m.start_time=x.temporal_moments[i].start_time;m.end_time=x.temporal_moments[i].end_time;m.surfels=x.temporal_moments[i].surfels;m.parent_moment=parent;m.evidence=x.temporal_moments[i].moment_hash;m.rootprint=compute_formal_moment_rootprint(m);parent=m.rootprint;c.moments.push_back(std::move(m));}c.id.clear();c.provenance={};return c;}
WorldCell export_world_cell_v2(const FormalWorldCell&c){WorldCell x;x.id=c.id;x.base_geometry=c.base_geometry;x.provenance=c.provenance;x.pha=c.pha;x.memory_capsule=c.memory_capsule;x.parent_rootprint=c.parent_rootprint;for(const auto&m:c.moments){Moment q;q.start_time=m.start_time;q.end_time=m.end_time;q.surfels=m.surfels;q.moment_hash=m.rootprint;x.temporal_moments.push_back(std::move(q));}return x;}
} // namespace keyxym
